Feature/aci 2 docker action initial version (#2)
* initial stab at docker action

* Update test.yaml

* refactor for docker token

* Fixing script permissions

* update to on PR

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,18 +1,32 @@
 name: Test Docker Build and Push
 
-on: push
+#On pr only
+on:
+  pull_request:
+    branches:
+      - main
+env:
+  REPO_NAME: actionsci
+  VERSION: 0.1.0-test
+  DIRECTORY: .
+  DOCKERFILE: ./Dockerfile
+  BUILD_ARGS: ''
+  REGISTRY_URL: docker.io
+  REGISTRY_USERNAME: burninmedia
+  REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
 
 jobs:
   build-and-push:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v4 
+        uses: actions/checkout@v4
+      
       # Simulate running the Docker build and push script
       - name: Run build-and-push script
         run: |
           . ./scripts/build-and-push.sh \
-            "${{ env.IMAGE_NAME }}" \
+            "${{ env.REGISTRY_USERNAME }}/${{ env.REPO_NAME }}" \
             "${{ env.VERSION }}" \
             "${{ env.DIRECTORY }}" \
             "${{ env.DOCKERFILE }}" \
@@ -20,12 +34,29 @@ jobs:
             "${{ env.REGISTRY_URL }}" \
             "${{ env.REGISTRY_USERNAME }}" \
             "${{ env.REGISTRY_PASSWORD }}"
-        env:
-          IMAGE_NAME: burninmedia/actionsci
-          VERSION: 0.1.0-test
-          DIRECTORY: .
-          DOCKERFILE: ./Dockerfile
-          BUILD_ARGS: ''
-          REGISTRY_URL: docker.io
-          REGISTRY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
-          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
+        
+      # Step that will delete the test image from repo using bash commands if previous step is successful
+      - name: Authenticate with Docker Hub and Obtain JWT
+        id: docker_auth
+        run: |
+          HUB_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"${{ secrets.DOCKER_USERNAME }}\", \"password\": \"${{ secrets.DOCKERHUB_TOKEN }}\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)
+          if [[ -z "$HUB_TOKEN" || "$HUB_TOKEN" == "null" ]]; then
+            echo "Authentication failed."
+            exit 1
+          fi
+          echo "HUB_TOKEN=${HUB_TOKEN}" >> $GITHUB_ENV
+
+      - name: Delete Docker Image Tag from Docker Hub
+        run: |
+          RESPONSE_CODE=$(curl -s -o response.json -w "%{http_code}" -X DELETE \
+            -H "Accept: application/json" \
+            -H "Authorization: JWT ${HUB_TOKEN}" \
+            https://hub.docker.com/v2/repositories/${{ env.REGISTRY_USERNAME }}/${{ env.REPO_NAME }}/tags/${{ env.VERSION }}/)
+
+          if [[ "${RESPONSE_CODE}" -eq 204 ]]; then
+            echo "Image tag deleted successfully."
+          else
+            echo "Failed to delete the image tag. Response code: ${RESPONSE_CODE}"
+            cat response.json
+            exit 1
+          fi
